ARG IMAGE_VARIANT=slim-buster
ARG OPENJDK_VERSION=11.0.13
ARG PYTHON_VERSION=3.9.8

FROM python:${PYTHON_VERSION}-${IMAGE_VARIANT} AS py3
FROM openjdk:${OPENJDK_VERSION}-${IMAGE_VARIANT}

COPY --from=py3 / /
COPY ./ /app

ARG PYSPARK_VERSION=3.2.1
RUN pip --no-cache-dir install pyspark==${PYSPARK_VERSION}

ENTRYPOINT ["python"]